# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#

parameters:
  - name: jobName
    type: string
    default: 'x86_windows'
jobs:
- job: ${{ parameters.jobName }}
  pool:
    name: PrWin-1ES
    demands: ImageVersionOverride -equals 2024.07.12
  workspace:
    clean: resources
  timeoutInMinutes: 2880 # 2 days
  steps:
  - task: AzureCLI@2
    displayName: '*** Test Modified Ports'
    inputs:
      azureSubscription: 'VcpkgPrFleet'
      scriptType: 'pscore'
      failOnStandardError: true
      scriptLocation: 'inlineScript'
      inlineScript: |
        & pwsh ./scripts/azure-pipelines/write-an-error.ps1
