environment:
  matrix:
    - TRIPLET: "x86-windows"
    - TRIPLET: "x64-windows"

build_script:
  - powershell -exec bypass scripts\bootstrap.ps1
  - cmd: for /D %%l in (ports\*) do .\vcpkg.exe install %%~nxl --triplet %TRIPLET%

matrix:
  fast_finish: true
