# Appveyor CI configuration for vcpkg project.
#
# Copyright 2018 Hiroshi Miura
#
image: Visual Studio 2017

shallow_clone: false

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  VCPKG_FEATURE_FLAGS: "binarycaching"
  
  matrix:
    - VCPKG_DEFAULT_TRIPLET: x86-windows
    - VCPKG_DEFAULT_TRIPLET: x86-windows-static
    - VCPKG_DEFAULT_TRIPLET: x64-windows
    - VCPKG_DEFAULT_TRIPLET: x64-windows-static
    - VCPKG_DEFAULT_TRIPLET: arm-uwp

cache:
  - archives

install:
  - ps: |
      ./scripts/bootstrap.ps1
      # Detect modified ports and make changes list
      # fetch upstream project which is necessary for forked project to compare with.
      git remote add upstream https://github.com/Microsoft/vcpkg.git
      git fetch -q upstream
      $env:targets = git diff --name-only upstream/master... |
          ?{$_ -match "ports/(?<change>.*?)/"} | %{$Matches.change} | Group-Object | % Name
      if([string]::IsNullOrWhitespace($targets)) { $env:targets = "zlib" }
      ./vcpkg.exe remove  $env:targets --recurse
      ./vcpkg.exe install $env:targets --recurse --keep-going --binarycaching

build: off

test: off

deploy: off

on_success:
  -ps: ./vcpkg.exe export $env:targets --zip

on_failure:
  -ps: $env:targets.Split(" ") | %{ 7z a $_-buildlog.zip buildtrees\$_\*.log }

artifacts:
  - path: '*.zip'
