# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#

jobs:
- job: x64_linux
  pool:
    name: PrLin-1ES-Pool
  workspace:
    clean: resources
  timeoutInMinutes: 1440 # 1 day
  steps:
  - task: AzureCLI@2
    displayName: '*** Test Modified Ports'
    inputs:
      azureSubscription: 'VcpkgPrFleet'
      scriptType: 'pscore'
      failOnStandardError: true
      scriptLocation: 'inlineScript'
      inlineScript: |
        Write-Error "This should fail the run"
