# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#

parameters:
  - name: jobName
    type: string
    default: 'x64_osx'
  - name: poolName
    type: string

jobs:
- job: ${{ parameters.jobName }}
  pool:
    name: ${{ parameters.poolName }}
  workspace:
    clean: resources
  timeoutInMinutes: 2880 # 2 days
  steps:
  - task: AzureCLI@2
    displayName: '*** Test Modified Ports'
    inputs:
      azureSubscription: 'VcpkgPrFleet'
      scriptType: 'pscore'
      failOnStandardError: true
      scriptLocation: 'inlineScript'
      inlineScript: |
        Write-Error "This should fail the run"
