# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#
jobs:
- template: windows/azure-pipelines.yml
  parameters:
    jobName: x86_windows

- template: osx/azure-pipelines.yml
  parameters:
    jobName: arm64_osx
    poolName: 'PrOsx-2024-07-12-arm64'

- template: linux/azure-pipelines.yml
  parameters:
    jobName: x64_linux
