# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#
variables:
  windows-pool: 'PrWin-2022-12-18'
  linux-pool: 'PrLin-2022-12-17'
  osx-pool: 'PrOsx-2022-02-04'

parameters:
  - name: vcpkgToolSha
    displayName: 'Custom SHA of vcpkg-tool to use rather than bootstrap'
    type: string
    default: 'use default'

jobs:
- template: osx/azure-pipelines.yml
  parameters:
    poolName: $(osx-pool)
    vcpkgToolSha: ${{ parameters.vcpkgToolSha }}
