# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#
variables:
  windows-pool: 'PrWin-2022-01-11'
  linux-pool: 'PrLin-2021-12-13'
  osx-pool: 'PrOsx-2022-02-04'

jobs:
- template: windows/azure-pipelines.yml
  parameters:
    triplet: x64-uwp
    jobName: x64_uwp
    poolName: $(windows-pool)

- template: windows/azure-pipelines.yml
  parameters:
    triplet: x64-uwp
    jobName: x64_uwp_2
    poolName: $(windows-pool)

- template: windows/azure-pipelines.yml
  parameters:
    triplet: x64-uwp
    jobName: x64_uwp_3
    poolName: $(windows-pool)

- template: windows/azure-pipelines.yml
  parameters:
    triplet: x64-uwp
    jobName: x64_uwp_4
    poolName: $(windows-pool)

- template: windows/azure-pipelines.yml
  parameters:
    triplet: x64-uwp
    jobName: x64_uwp_5
    poolName: $(windows-pool)
