name: Refresh NuGet libraries (windows)

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

on:
  push:
    branches:
      - "test-*"
      - "hpcc-platform-*"

jobs:
  build:
    strategy:
      matrix:
        triplet: ["x64-linux", "x64-windows", "x86-windows", "x64-osx"]
        include:
          - os: "ubuntu-latest"
            triplet: "x64-linux"
            mono: "mono"
            sudo: "sudo"
          - os: "windows-latest"
            triplet: "x64-windows"
            mono: ""
            sudo: ""
          - os: "windows-latest"
            triplet: "x86-windows"
            mono: ""
            sudo: ""
          - os: "macos-10.15"
            triplet: "x64-osx"
            mono: "mono"
            sudo: "sudo"
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: "Remove builtin vcpkg (old)"
        working-directory: .
        shell: "bash"
        run: |
          ${{ matrix.sudo }} rm -rf "$VCPKG_INSTALLATION_ROOT"

      - name: Check out source code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Bootstrap vcpkg"
        working-directory: .
        shell: "bash"
        run: |
          ./bootstrap-vcpkg.sh

      - name: "Setup NuGet Credentials"
        working-directory: .
        shell: "bash"
        run: |
          ${{ matrix.mono }} `./vcpkg fetch nuget | tail -n 1` \
            sources add \
            -source "https://nuget.pkg.github.com/hpcc-systems/index.json" \
            -storepasswordincleartext \
            -name "GitHub" \
            -username "hpcc-systems" \
            -password "${{ secrets.GITHUB_TOKEN }}"
          ${{ matrix.mono }} `./vcpkg fetch nuget | tail -n 1` \
            setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -source "https://nuget.pkg.github.com/hpcc-systems/index.json"

      - name: "vcpkg package refresh"
        working-directory: .
        shell: "bash"
        run: |
          ./vcpkg install --keep-going --triplet ${{ matrix.triplet }}
