name: Refresh NuGet libraries (windows)

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

on:
  push:
    branches:
      - "hpcc-platform-*"

jobs:
  build:
    strategy:
      matrix:
        triplet: ["x86-windows", "x64-windows"]
        include:
          - os: "windows-2019"
            triplet: "x86-windows"
          - os: "windows-2019"
            triplet: "x64-windows"
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: "Remove builtin vcpkg (old)"
        working-directory: .
        shell: "bash"
        run: |
          rm -rf "$VCPKG_INSTALLATION_ROOT"

      - name: Check out source code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Bootstrap vcpkg"
        working-directory: .
        shell: "bash"
        run: |
          ./bootstrap-vcpkg.sh

      - name: "Setup NuGet Credentials"
        working-directory: .
        shell: "bash"
        run: |
          `./vcpkg.exe fetch nuget | tail -n 1` \
            sources add \
            -source "https://nuget.pkg.github.com/hpcc-systems/index.json" \
            -storepasswordincleartext \
            -name "GitHub" \
            -username "hpcc-systems" \
            -password "${{ secrets.GITHUB_TOKEN }}"
          `./vcpkg.exe fetch nuget | tail -n 1` \
            setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -source "https://nuget.pkg.github.com/hpcc-systems/index.json"

      - name: "vcpkg package refresh"
        working-directory: .
        shell: "bash"
        run: >
          ./vcpkg.exe install --keep-going icu zlib openssl libxslt winflexbison libuv librdkafka lz4 hiredis tbb aws-sdk-cpp rapidjson h3 libyaml azure-storage-cpp jwt-cpp libgit2 --triplet ${{ matrix.triplet }}
